project:
  type: website
  resources:
    - CNAME

website:
  title: "Trackyverse"
  site-url: "https://trackyverse.org"
  navbar:
    logo: hex_logo.png
    left:
      - href: index.qmd
        text: Home
    tools:
      - icon: github
        menu:
          - text: Trackyverse Org
            href: https://github.com/trackyverse
          - text: Source Code
            href: https://github.com/trackyverse/trackyverse.org

format:
  html:
    theme:
      - litera
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto


