on:
  workflow_dispatch:
  pull_request:
  push:
    branches: main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

name: Quarto Publish

jobs:
  quarto:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - name: Set up R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::knitr
            any::rmarkdown
            any::quarto

      - name: Check that PR will render
        if: github.event_name == 'pull_request'
        uses: quarto-dev/quarto-actions/render@v2

      - name: Render and Publish
        if: github.event_name != 'pull_request'
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}